apiVersion: v1
kind: Service
metadata:
  namespace: dev
  labels:
    app: game-server
  name: game-server
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: game-server
  type: LoadBalancer